### ISSUE TITLE
hey again, just a tiny issue i guess

### ISSUE THREAD

**Issue by Maureks** [Marttins011/mt-atmrobbery#1]
the server event to the robbery cooldown does not exist in the server.lua , you can rob the same atm over and over again non-stop!

thanks for the attention

**Comment by Marttins011** [comment]
Done, i added the Cooldown and now you need a trojan_usb to use that!

**Comment by Maureks** [comment]
I noticed , and downloaded it right away eheh , going to test it soon , also downloaded your other scripts , nice job man , keep it up ! Thank you so much !

**Comment by Maureks** [comment]
Hey , the qb-target export is not working anymore, had to create one manually , and it worked and the cooldown too, despite giving an error , but , it didn't took the trojan_usb from the inventory.

Also , the fxmanifest , looks for a config file that does not exist , giving an error when (GlobalConfig)

Thanks once again!

**Comment by Marttins011** [comment]
This issue about the config is fixed!

**Comment by Marttins011** [comment]
I use always the same fxmanifest on all of my scripts so i do t delete this but, you can delete if you want
